apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill
  labels:
    {{- include "bill.labels" . | nindent 4}}
    app.kubernetes.io/component: bill
spec:
  replicas: {{ .Values.bill.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: bill
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bill
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: bill
          image: {{ .Values.bill.image }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: BILL_DB_URL 
          ports:
            - name: http
              containerPort: 3337
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3337
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3337