apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "bill.labels" . | nindent 4}}
type: Opaque
data:
  bill_db_url: {{ .Values.billMongoUrl | b64enc }}