apiVersion: v1
kind: Service
metadata: 
  name: bill
  labels:
    {{- include "bill.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec: 
  selector:
    app.kubernetes.io/name: bill
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - targetPort: 3337
      protocol: TCP
      name: http
      port: 3337