name: Okteto Deployment

on:
  push:
    branches: [ main ]

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Okteto Login
          uses: okteto/login@latest
          with:
            token: ${{secrets.OKTETO_BILL_TOKEN}}

        - name: Okteto deploy
          uses: resinas/okteto-push@v1.0.2
          with:
            namespace: hygeia-care-bills-mjcastrous
